species: Arabidopsis

seq_info:
  type: ChIP-Seq
  mode: PE
  replicate: 2

path: /cluster/home/qjzheng/Project/YHH0047_20191111/ChIP-Seq/fastq/

samples:
  - Input_ING.1
  - Input_ING.2
  - Input_WT.1
  - Input_WT.2
  - IP_ING.1
  - IP_ING.2
  - IP_WT.1
  - IP_WT.2

treat:
  - IP_ING.1
  - IP_ING.2
  - IP_WT.1
  - IP_WT.2

control:
  - Input_ING.1
  - Input_ING.2
  - Input_WT.1
  - Input_WT.2

olp:
# 1.see Factor and Replicate collumns in sample_sheet.csv; 2. don't use '_' 
  - ING:1.2
  - WT:1.2

peak1: 
  - TYLCV-1_a-H3K27me3_c_TYLCV-1_Input
 
peak2: 
  - EV-1_a-H3K27me3_c_EV-1_Input
 
diff.mask:
  - H3K27me3-TYLCV,H3K27me3-EV^H3K27me3-TYLCV-C3mut,H3K27me3-EV^H3K27me3-TYLCV-C3mut,H3K27me3-TYLCV^H3-TYLCV,H3-EV^H3-TYLCV-C3mut,H3-EV^H3-TYLCV-C3mut,H3-TYLCV
  
cpu: 30

Rscript_path: /cluster/home/xfu/R/3.5.1/bin/Rscript

RepeatMasker: /cluster/home/xfu/Git/MakerP/maker/exe/RepeatMasker/RepeatMasker

motif: /cluster/home/xfu/Git/MEME/motifs/JASPAR2018_CORE_plants_non-redundant_pfms_meme.txt

conda_path: /cluster/home/xfu/miniconda2/envs/gmatic/bin

adapter: /cluster/home/xfu/miniconda2/envs/gmatic/share/trimmomatic/adapters/TruSeq3-PE-2.fa

#p: 1e-5
p: 1e-2

# Arabidopsis
index: /cluster/home/xfu/Gmatic7/genome/tair10/bowtie2/tair10
 
chromSize: /cluster/home/xfu/Gmatic7/genome/tair10/tair10.chromSize
 
fasta: /cluster/home/xfu/Gmatic7/genome/tair10/tair10.fa
 
txdb: /cluster/home/xfu/Gmatic7/gene/tair10/txdb/tair10_txdb.sqlite
 
gene_anno: /cluster/home/xfu/Gmatic7/gene/tair10/tair10_gene_anno.tsv
 
gene_bed: /cluster/home/xfu/Gmatic7/gene/tair10/tair10_gene.bed
 
IGV: /cluster/home/xfu/igv/genomes/tair10.genome
 
gsize: 119667750

# Nicotiana benthamiana
#index: /cluster/home/xfu/Gmatic7/genome/Niben/bowtie2/Niben101
# 
#chromSize: /cluster/home/xfu/Gmatic7/genome/Niben/Niben101.chromSize
# 
#fasta: /cluster/home/xfu/Gmatic7/genome/Niben/Niben101.fa
# 
#txdb: /cluster/home/xfu/Gmatic7/gene/Niben/txdb/Niben101_txdb.sqlite
# 
#gene_anno: /cluster/home/xfu/Gmatic7/gene/Niben/Niben101_gene_anno_ath.tsv
# 
#gene_bed: /cluster/home/xfu/Gmatic7/gene/Niben/Niben101_gene.bed
# 
#IGV: /cluster/home/xfu/igv/genomes/Niben101.genome
# 
#gsize: 2969810994
#

