species: Arabidopsis thaliana

seq_info:
  type: ChIP-Seq (EBS protein)
  mode: PE
  replicate: 3

path: /var/data/raw_data/HYH_EBS2_ChIP_PE_2sam_3rep/fastq

samples:
  - EBS-1.chip
  - EBS-2.chip
  - EBS-3.chip
  - EBS-1.input
  - EBS-2.input
  - EBS-3.input

treat:
  - EBS-1
  - EBS-2
  - EBS-3

sample_info:
  EBS-1: EBS.2-1
  EBS-2: EBS.2-5-1
  EBS-3: EBS.2-5-2

peak1:
  - .

peak2:
  - .

index: /home/xfu/Gmatic5/genome/tair10/tair10

txdb: /home/xfu/Gmatic6/gene/tair10/tair10_txdb.sqlite

gene2go: /home/xfu/Gmatic6/gene/tair10/tair10_gene2GOterm.tsv

cpu: 30

adapter: /home/xfu/miniconda2/envs/gmatic/share/trimmomatic/adapters/TruSeq3-PE-2.fa

insert: 1000

IGV: /home/xfu/igv/genomes/tair10.genome

gsize: 119667750

p: 1e-2

olp.mask: .

diff.mask: .
