species: Arabidopsis thaliana

seq_info:
  type: ChIP-Seq
  mode: PE
  replicate: 3

path: /home/xfu/Project/HYH_20180911/ChIP-Seq/fastq/

samples:
  - Input_5DAG_lec1l1l.1
  - Input_5DAG_lec1l1l.2
  - Input_5DAG_lec1l1l.3
  - Input_5DAG_WT.1
  - Input_5DAG_WT.2
  - Input_5DAG_WT.3
  - IP_5DAG_lec1l1l.1
  - IP_5DAG_lec1l1l.2
  - IP_5DAG_lec1l1l.3
  - IP_5DAG_WT.1
  - IP_5DAG_WT.2
  - IP_5DAG_WT.3

treat:
  - 5DAG_lec1l1l.1
  - 5DAG_lec1l1l.2
  - 5DAG_lec1l1l.3
  - 5DAG_WT.1
  - 5DAG_WT.2
  - 5DAG_WT.3

olp: 
# don't use '_' 
  - WT:1.2.3
  - lec1l1l:1.2.3

diff.mask:
  - lec1l1l,WT
  
cpu: 30

Rscript_path: /cluster/home/xfu/R/3.5.1/bin/Rscript

RepeatMasker: /cluster/home/xfu/Git/MakerP/maker/exe/RepeatMasker/RepeatMasker

motif: /cluster/home/xfu/Git/MEME/motifs/JASPAR2018_CORE_plants_non-redundant_pfms_meme.txt

conda_path: /cluster/home/xfu/miniconda2/envs/gmatic/bin

adapter: /cluster/home/xfu/miniconda2/envs/gmatic/share/trimmomatic/adapters/TruSeq3-PE-2.fa

p: 1e-5

# Arabidopsis
index: /cluster/home/xfu/Gmatic7/genome/tair10/bowtie2/tair10
 
chromSize: /cluster/home/xfu/Gmatic7/genome/tair10/tair10.chromSize
 
fasta: /cluster/home/xfu/Gmatic7/genome/tair10/tair10.fa
 
txdb: /cluster/home/xfu/Gmatic7/gene/tair10/txdb/tair10_txdb.sqlite
 
gene_anno: /cluster/home/xfu/Gmatic7/gene/tair10/tair10_gene_anno.tsv
 
gene_bed: /cluster/home/xfu/Gmatic7/gene/tair10/tair10_gene.bed
 
IGV: /cluster/home/xfu/igv/genomes/tair10.genome
 
gsize: 119667750

# Nicotiana benthamiana
#index: /cluster/home/xfu/Gmatic7/genome/Niben/bowtie2/Niben101
# 
#chromSize: /cluster/home/xfu/Gmatic7/genome/Niben/Niben101.chromSize
# 
#fasta: /cluster/home/xfu/Gmatic7/genome/Niben/Niben101.fa
# 
#txdb: /cluster/home/xfu/Gmatic7/gene/Niben/txdb/Niben101_txdb.sqlite
# 
#gene_anno: /cluster/home/xfu/Gmatic7/gene/Niben/Niben101_gene_anno_ath.tsv
# 
#gene_bed: /cluster/home/xfu/Gmatic7/gene/Niben/Niben101_gene.bed
# 
#IGV: /cluster/home/xfu/igv/genomes/Niben101.genome
# 
#gsize: 2969810994
